### PR TITLE
Add PiKISS GUI

### PR DESCRIPTION
**Pull request by Jai-JAP**

### CODE REVIEW

**Comment by Jai-JAP** [comment]
@jmcerrejon

**Comment by jmcerrejon** [comment]
I don't understand the modification of the script gl4es.sh

**Comment by Jai-JAP** [comment]
Oops accidentally saved to wrong file

**Comment by Jai-JAP** [comment]
@jmcerrejon Fixed that....

**Comment by Jai-JAP** [comment]
@jmcerrejon

**Comment by jmcerrejon** [comment]
Finally you go to another direction, and It's OK. Thanks.

**Pull request closed without merging**
