### PR TITLE
fix looping questions

### PR DESCRIPTION
**Pull request by Itai-Nelken**

### CODE REVIEW

**Comment by Itai-Nelken** [comment]
in some of the questions for extra features, `apt` wasn't being run as root. so I fixed that as well.
currently testing the script.

**Comment by Itai-Nelken** [comment]
it fails in line 113 (nothing to do with my fixes).
make doesn't find a makefile.

**Comment by Itai-Nelken** [comment]
this is the error:
```
/home/pi/piKiss/scripts/devs/qt5.sh: line 112: ../qt-everywhere-src-5.12.8/configure: No such file or directory
make: *** No targets specified and no makefile found.  Stop.
```

**Comment by jmcerrejon** [comment]
Sorry Itai, but finally I'm rewriting the script by myself. Thank you anyway! 😄

**Pull request closed without merging**
